(function(){'use strict';const aa=["DEBUG","INFO","WARN","ERROR"];var ba="main",ca=null;function ia(a,b,d){if(!(1>a)){var g="EagRuntimeJS: ["+(new Date).toLocaleTimeString()+"]["+ba+"/"+(aa[a]||"UNKNOWN")+"] ";a:{if(0<d.length){for(var q=[],w=0;w<d.length;++w){var C=b.indexOf("{}");if(-1!=C)q.push(b.substring(0,C)),q.push(d[w]),b=b.substring(C+2);else break}if(0<q.length){q.push(b);d=q.join("");break a}}d=b}b=g+d;3<=a?console.error(b):console.log(b);ca&&ca(b,3<=a)}}function c(a,...b){ia(1,a,b)}
function h(a,...b){ia(3,a,b)}function la(a,b){if(b){if(b.message?ia(3,'{}: {} - "{}"',[a,b.name,b.message]):ia(3,"{}: {}",[a,b.name]),"string"===typeof b.stack)for(b=ma(b.stack),a=0;a<b.length;++a)ia(3,"    at "+b[a],[])}else ia(3,"{}: <null>",[a])}function pa(a){return function(){h("Unsupported function called: {}.{}",a);return 0}}function z(a,b){a[b]=pa(b)}function ra(a){return new Promise(function(b){setTimeout(b,a)})}
class sa{constructor(){this.i=this.g=null;this.m=0}A(){return this.m}push(a){this.i&&(this.i._next=a);this.i=a;this.g||(this.g=a);++this.m}s(){if(this.g){const a=this.g;(this.g=a._next||null)?a._next=null:this.i=null;--this.m;return a}return null}};var va={},A={},wa={},xa={},ya={},F={},za={},H={},Da={},Ea=null,Fa=null,Ga=null,Ha=null,Ia=null,I=null,Ka=null,K=null,S=null,La=null,Ma=!1,Na=0,T=null,Oa=null,Ra=null,Sa=null,Ta=null,Ua=null,Va=null,Wa=null,Xa=null,Ya=!1,Za=!1;const $a=[];var ab=null,vb=null,wb=null,xb=null,yb="_eaglercraftX",zb=!1,Ab=!1,Bb=!1,Cb=!1,Db=!0,Eb=!0,Fb=!1;
function Gb(){"string"===typeof I.localStorageNamespace&&(yb=I.localStorageNamespace);"boolean"===typeof I.openDebugConsoleOnLaunch&&(zb=I.openDebugConsoleOnLaunch);"boolean"===typeof I.fixDebugConsoleUnloadListener&&(Ab=I.fixDebugConsoleUnloadListener);"boolean"===typeof I.forceWebGL1&&(Bb=I.forceWebGL1);"boolean"===typeof I.forceWebGL2&&(Cb=I.forceWebGL2);"boolean"===typeof I.allowExperimentalWebGL1&&(Db=I.allowExperimentalWebGL1);"boolean"===typeof I.useWebGLExt&&(Eb=I.useWebGLExt);"boolean"===
typeof I.useDelayOnSwap&&(Fb=I.useDelayOnSwap)}
async function Hb(){function a(){try{q=new AudioContext}catch(C){la("Could not initialize audio context",C)}}Gb();ca=Ib;"yes"!==window.__isEaglerX188UnloadListenerSet&&(window.onbeforeunload=function(){window.__curEaglerX188UnloadListenerCB&&window.__curEaglerX188UnloadListenerCB();return!1},window.__isEaglerX188UnloadListenerSet="yes");c("Initializing EagRuntime JS context...");await Jb();Kb();Ka.classList.add("_eaglercraftX_root_element");Ka.style.overflow="hidden";for(var b=null,d;d=Ka.lastChild;)b||=
d,Ka.removeChild(d);K=document.createElement("div");K.classList.add("_eaglercraftX_wrapper_element");K.style.position="relative";K.style.width="100%";K.style.height="100%";K.style.overflow="hidden";K.style.backgroundColor="black";Ka.appendChild(K);b&&(b.style.position="absolute",b.style.top="0px",b.style.left="0px",b.style.right="0px",b.style.bottom="0px",b.style.zIndex="2",b.classList.add("_eaglercraftX_early_splash_element"),K.appendChild(b));await ra(10);d=window.devicePixelRatio;b=d*K.clientWidth|
0;d=d*K.clientHeight|0;c("Initializing audio context");if("function"===typeof document.exitPointerLock){var g=navigator.userAgent;null!==g?(g=g.toLowerCase(),Ya=-1!==g.indexOf("mobi")||-1!==g.indexOf("tablet")):Ya=!1}else Ya=!0;var q=null;!Ya&&navigator.userActivation&&navigator.userActivation.hasBeenActive?a():(g=document.createElement("div"),g.classList.add("_eaglercraftX_press_any_key_image"),g.style.position="absolute",g.style.top="0px",g.style.left="0px",g.style.right="0px",g.style.bottom="0px",
g.style.width="100%",g.style.height="100%",g.style.zIndex="3",g.style.touchAction="pan-x pan-y",g.style.background='center / contain no-repeat url("'+Ga+'"), left / 1000000% 100% no-repeat url("'+Ga+'") white',g.style.setProperty("image-rendering","pixelated"),K.appendChild(g),await new Promise(function(C,L){function G(){if(!O){O=!0;Ya?K.removeChild(P):(window.removeEventListener("keydown",G),K.removeEventListener("mousedown",G),K.removeEventListener("touchstart",G));try{a()}catch(B){L(B);return}C()}}
var O=!1;if(Ya){var P=document.createElement("div");P.classList.add("_eaglercraftX_mobile_press_any_key");P.setAttribute("style","position:absolute;background-color:white;font-family:sans-serif;top:10%;left:10%;right:10%;bottom:10%;border:5px double black;padding:calc(5px + 7vh) 15px;text-align:center;font-size:20px;user-select:none;z-index:10;");P.innerHTML='<h3 style="margin-block-start:0px;margin-block-end:0px;margin:20px 5px;">Mobile Browser Detected</h3><p style="margin-block-start:0px;margin-block-end:0px;margin:20px 5px;">Warning: EaglercraftX WASM-GC requires a lot of memory and may not be stable on most mobile devices!</p><p style="margin-block-start:0px;margin-block-end:0px;margin:20px 2px;"><button style="font: 24px sans-serif;font-weight:bold;" class="_eaglercraftX_mobile_launch_client">Launch EaglercraftX</button></p><p style="margin-block-start:0px;margin-block-end:0px;margin:25px 5px;">(Tablets and phones with large screens work best)</p>';
P.querySelector("._eaglercraftX_mobile_launch_client").addEventListener("click",G);K.appendChild(P)}else window.addEventListener("keydown",G),K.addEventListener("mousedown",G),K.addEventListener("touchstart",G)}),K.removeChild(g));q?Lb(q):Mb();c("Creating main canvas");S=document.createElement("canvas");S.classList.add("_eaglercraftX_canvas_element");S.style.width="100%";S.style.height="100%";S.style.zIndex="1";S.style.touchAction="pan-x pan-y";S.style.setProperty("-webkit-touch-callout","none");
S.style.setProperty("-webkit-tap-highlight-color","rgba(255, 255, 255, 0)");S.style.setProperty("image-rendering","pixelated");S.width=b;S.height=d;K.appendChild(S);await Nb();c("Creating WebGL context");K.addEventListener("webglcontextcreationerror",function(C){h("[WebGL Error]: {}",C.statusMessage)});b={antialias:!1,depth:!1,powerPreference:"high-performance",desynchronized:!0,preserveDrawingBuffer:!1,premultipliedAlpha:!1,alpha:!1};g=!1;if(Cb){c("Note: Forcing WebGL 2.0 context");d=300;var w=S.getContext("webgl2",
b);if(!w)return Ob("WebGL 2.0 is not supported on this device!"),!1}else if(Bb){if(c("Note: Forcing WebGL 1.0 context"),d=200,w=S.getContext("webgl",b),!w)if(Db){if(g=!0,w=S.getContext("experimental-webgl",b),!w)return Ob("WebGL is not supported on this device!"),!1}else return Ob("WebGL is not supported on this device!"),!1}else if(d=300,w=S.getContext("webgl2",b),!w&&(d=200,w=S.getContext("webgl",b),!w))if(Db){if(g=!0,w=S.getContext("experimental-webgl",b),!w)return Ob("WebGL is not supported on this device!"),
!1}else return Ob("WebGL is not supported on this device!"),!1;g&&alert('WARNING: Detected "experimental" WebGL 1.0 support, certain graphics API features may be missing, and therefore EaglercraftX may malfunction and crash!');Na=d;La=w;Ma=g;Pb(w,d);c("OpenGL Version: {}",H.glGetString(7938));c("OpenGL Renderer: {}",H.glGetString(7937));b=H.dumpActiveExtensions();if(0===b.length)c("Unlocked the following OpenGL ES extensions: (NONE)");else for(b.sort(),c("Unlocked the following OpenGL ES extensions:"),
d=0;d<b.length;++d)c(" - {}",b[d]);H.glClearColor(0,0,0,1);H.glClear(16384);await ra(20);c("EagRuntime JS context initialization complete");return!0}
async function Qb(){Gb();ca=function(a,b){postMessage({ch:"~!LOGGER",txt:a,err:b})};c("Initializing EagRuntime worker JS context...");await Jb();z(A,"setClipboard");z(A,"getClipboard");z(A,"displayFileChooser");z(A,"fileChooserHasResult");z(A,"getFileChooserResult");z(A,"clearFileChooserResult");z(A,"downloadFileWithNameU8");z(A,"downloadFileWithNameA");z(A,"downloadScreenshot");z(A,"showDebugConsole");z(A,"addLogMessage");z(A,"isShowingDebugConsole");z(A,"getFaviconURL");z(A,"setResetSettingsCallback");
Mb();z(F,"keyboardLayoutSupported");z(F,"iterateKeyboardLayout");z(F,"updateCanvasSize");z(F,"updatePlatformAndSleep");z(F,"isVSyncSupported");z(F,"mouseSetGrabbed");z(F,"isMouseGrabSupported");z(F,"isMouseGrabbed");z(F,"isPointerLocked");z(F,"supportsFullscreen");z(F,"toggleFullscreen");z(F,"isFullscreen");z(F,"touchSetOpenKeyboardZone");z(F,"touchCloseDeviceKeyboard");z(F,"touchIsDeviceKeyboardOpenMAYBE");z(F,"gamepadSupported");z(F,"isVisualViewport");z(H,"getCapBits");z(H,"glEnable");z(H,"glDisable");
z(H,"glClearColor");z(H,"glClearDepth");z(H,"glClear");z(H,"glDepthFunc");z(H,"glDepthMask");z(H,"glCullFace");z(H,"glViewport");z(H,"glBlendFunc");z(H,"glBlendFuncSeparate");z(H,"glBlendEquation");z(H,"glBlendColor");z(H,"glColorMask");z(H,"glDrawBuffers");z(H,"glReadBuffer");z(H,"glReadPixels");z(H,"glPolygonOffset");z(H,"glLineWidth");z(H,"glGenBuffers");z(H,"glGenTextures");z(H,"glCreateProgram");z(H,"glCreateShader");z(H,"glCreateFramebuffer");z(H,"glCreateRenderbuffer");z(H,"glGenQueries");
z(H,"glDeleteBuffers");z(H,"glDeleteTextures");z(H,"glDeleteProgram");z(H,"glDeleteShader");z(H,"glDeleteFramebuffer");z(H,"glDeleteRenderbuffer");z(H,"glDeleteQueries");z(H,"glBindBuffer");z(H,"glBufferData");z(H,"glBufferSubData");z(H,"glEnableVertexAttribArray");z(H,"glDisableVertexAttribArray");z(H,"glVertexAttribPointer");z(H,"glActiveTexture");z(H,"glBindTexture");z(H,"glTexParameterf");z(H,"glTexParameteri");z(H,"glTexImage3D");z(H,"glTexImage2D");z(H,"glTexSubImage2D");z(H,"glCopyTexSubImage2D");
z(H,"glTexStorage2D");z(H,"glPixelStorei");z(H,"glGenerateMipmap");z(H,"glShaderSource");z(H,"glCompileShader");z(H,"glGetShaderi");z(H,"glGetShaderInfoLog");z(H,"glUseProgram");z(H,"glAttachShader");z(H,"glDetachShader");z(H,"glLinkProgram");z(H,"glGetProgrami");z(H,"glGetProgramInfoLog");z(H,"glDrawArrays");z(H,"glDrawElements");z(H,"glDrawRangeElements");z(H,"glFlush");z(H,"glScissor");z(H,"glBindAttribLocation");z(H,"glGetAttribLocation");z(H,"glGetUniformLocation");z(H,"glGetUniformBlockIndex");
z(H,"glBindBufferRange");z(H,"glUniformBlockBinding");z(H,"glUniform1f");z(H,"glUniform2f");z(H,"glUniform3f");z(H,"glUniform4f");z(H,"glUniform1i");z(H,"glUniform2i");z(H,"glUniform3i");z(H,"glUniform4i");z(H,"glUniformMatrix2fv");z(H,"glUniformMatrix3fv");z(H,"glUniformMatrix4fv");z(H,"glUniformMatrix3x2fv");z(H,"glUniformMatrix4x2fv");z(H,"glUniformMatrix4x3fv");z(H,"glBindFramebuffer");z(H,"glCheckFramebufferStatus");z(H,"glBlitFramebuffer");z(H,"glRenderbufferStorage");z(H,"glFramebufferTexture2D");
z(H,"glFramebufferTextureLayer");z(H,"glBindRenderbuffer");z(H,"glFramebufferRenderbuffer");z(H,"glGetInteger");z(H,"glGetError");z(H,"getAllExtensions");z(H,"dumpActiveExtensions");z(H,"glGetString");z(H,"glGenVertexArrays");z(H,"glDeleteVertexArrays");z(H,"glBindVertexArray");z(H,"glVertexAttribDivisor");z(H,"glDrawArraysInstanced");z(H,"glDrawElementsInstanced");z(H,"isContextLost");c("EagRuntime worker JS context initialization complete")}
function Rb(a){T=a.buffer;c("WebAssembly direct memory resized to {} MiB",.01*(T.byteLength/1024/10.24|0));Oa=new Uint8Array(T);Ra=new Int8Array(T);Sa=new Uint16Array(T);Ta=new Int16Array(T);Va=new Uint32Array(T);Ua=new Int32Array(T);Wa=new Float32Array(T);Sb()}function Sb(){Xa&&Xa(Ra,Oa,Ta,Sa,Ua,Va,Wa)}const Tb=new sa;function Y(a,b,d){Tb.push({eventType:a<<5|b,eventObj:d,_next:null})}let Ub=/.+:wasm-function\[[0-9]+]:0x([0-9a-f]+).*/;
function ma(a){if(!a)return null;const b=[];for(let d of a.split("\n")){if(Ea&&(a=Ub.exec(d),null!==a&&2<=a.length&&(a=parseInt(a[1],16),!isNaN(a))))try{const g=Ea([a]);if(0<g.length){for(let q of g)b.push(""+q.className+"."+q.method+"("+q.file+":"+q.line+")");continue}}catch(g){}d=d.trim();d.startsWith("at ")&&(d=d.substring(3));b.push(d)}return b}
function Vb(){var a=document.createElement("button");a.setAttribute("style","margin-left:10px;");a.innerText="Reset Settings";a.addEventListener("click",function(){wb?wb():window.alert("Local storage has not been initialized yet")});const b=document.createElement("button");b.setAttribute("style","margin-left:10px;");b.innerText="Open Debug Console";b.addEventListener("click",function(){vb?vb():window.alert("Debug console has not been initialized yet")});var d=document.createElement("div");d.setAttribute("style",
"position:absolute;bottom:5px;right:0px;");d.appendChild(a);d.appendChild(b);a=document.createElement("div");a.setAttribute("style","position:relative;");a.appendChild(d);d=document.createElement("div");d.classList.add("_eaglercraftX_crash_tools_element");d.setAttribute("style","z-index:101;position:absolute;top:135px;left:10%;right:10%;height:0px;");d.appendChild(a);return d}
function Wb(a){const b=a?ma(a.stack):null;a="Native Browser Exception\n----------------------------------\n  Line: "+(a&&"string"===typeof a.fileName?a.fileName:"unknown")+":"+(a&&"number"===typeof a.lineNumber?a.lineNumber:"unknown")+":"+(a&&"number"===typeof a.columnNumber?a.columnNumber:"unknown")+"\n  Type: "+(a&&"string"===typeof a.name?a.name:"unknown")+"\n  Desc: "+(a&&"string"===typeof a.message?a.message:"null")+"\n----------------------------------\n\nDeobfuscated stack trace:\n    at "+
(b?b.join("\n    at "):"null")+"\n\nThis exception was not handled by the WASM binary\n";"undefined"!==typeof window?Xb(a,!0):h("\n{}",a)}
function Xb(a,b){h("Game crashed!");var d="Game Crashed! I have fallen and I can't get up!\n\n"+a+"\n\n",g='eaglercraft.version = "'+$a[0]+'"\neaglercraft.minecraft = "'+$a[2]+'"\neaglercraft.brand = "'+$a[1]+'"\n\n'+Yb()+"\nwindow.eaglercraftXOpts = "+JSON.stringify(I)+"\n\ncurrentTime = "+(new Date).toLocaleString()+"\n\n"+Zb("userAgent")+Zb("vendor")+Zb("language")+Zb("hardwareConcurrency")+Zb("deviceMemory")+Zb("platform")+Zb("product")+$b()+"\n"+ac("localStorage")+ac("sessionStorage")+ac("indexedDB")+
"\nrootElement.clientWidth = "+(K?K.clientWidth:"undefined")+"\nrootElement.clientHeight = "+(K?K.clientHeight:"undefined")+"\n"+ac("innerWidth")+ac("innerHeight")+ac("outerWidth")+ac("outerHeight")+ac("devicePixelRatio")+bc("availWidth")+bc("availHeight")+bc("colorDepth")+bc("pixelDepth")+"\n"+cc()+"\n",q=d+g;const w=[];try{"object"===typeof I&&"object"===typeof I.hooks&&"function"===typeof I.hooks.crashReportShow&&I.hooks.crashReportShow(q,function(C){w.push(C)})}catch(C){la("Uncaught exception invoking crash report hook",
C)}if(Za){h("");h("An additional crash report was supressed:");q=a.split(/[\r\n]+/);for(a=0;a<q.length;++a)h("  {}",q[a]);if(0<w.length)for(a=0;a<w.length;++a)if(q=w[a]){h("");h("  ----------[ CRASH HOOK ]----------");q=q.split(/[\r\n]+/);for(a=0;a<q.length;++a)h("  {}",q[a]);h("  ----------------------------------")}}else{Za=!0;if(0<w.length){q=d+"Got the following messages from the crash report hook registered in eaglercraftXOpts:\n\n";for(a=0;a<w.length;++a)q+="----------[ CRASH HOOK ]----------\n"+
w[a]+"\n----------------------------------\n\n";q+=g}(g=K||Ka)?(b&&h("\n{}",q),b=document.createElement("img"),a=document.createElement("div"),b.setAttribute("style","z-index:100;position:absolute;top:10px;left:calc(50% - 151px);"),b.src=Ha,a.setAttribute("style","z-index:100;position:absolute;top:135px;left:10%;right:10%;bottom:50px;background-color:white;border:1px solid #cccccc;overflow-x:hidden;overflow-y:scroll;overflow-wrap:break-word;white-space:pre-wrap;font: 14px monospace;padding:10px;"),
a.classList.add("_eaglercraftX_crash_element"),g.appendChild(b),g.appendChild(a),g.appendChild(Vb()),a.appendChild(document.createTextNode(q)),ab&&ab(),window.__curEaglerX188UnloadListenerCB=null):(alert("Root element not found, crash report was printed to console"),h("\n{}",q))}}
function Ob(a){if(!Za){Za=!0;var b=K||Ka;h("Compatibility error: {}",a);if(b){var d=document.createElement("img"),g=document.createElement("div");d.setAttribute("style","z-index:100;position:absolute;top:10px;left:calc(50% - 151px);");d.src=Ha;g.setAttribute("style","z-index:100;position:absolute;top:135px;left:10%;right:10%;bottom:50px;background-color:white;border:1px solid #cccccc;overflow-x:hidden;overflow-y:scroll;font:18px sans-serif;padding:40px;");g.classList.add("_eaglercraftX_incompatible_element");
b.appendChild(d);b.appendChild(g);b.appendChild(Vb());g.innerHTML='<h2><svg style="vertical-align:middle;margin:0px 16px 8px 8px;" xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48" fill="none"><path stroke="#000000" stroke-width="3" stroke-linecap="square" d="M1.5 8.5v34h45v-28m-3-3h-10v-3m-3-3h-10m15 6h-18v-3m-3-3h-10"/><path stroke="#000000" stroke-width="2" stroke-linecap="square" d="M12 21h0m0 4h0m4 0h0m0-4h0m-2 2h0m20-2h0m0 4h0m4 0h0m0-4h0m-2 2h0"/><path stroke="#000000" stroke-width="2" stroke-linecap="square" d="M20 30h0 m2 2h0 m2 2h0 m2 2h0 m2 -2h0 m2 -2h0 m2 -2h0"/></svg>+ This device is incompatible with Eaglercraft&ensp;:(</h2><div style="margin-left:40px;"><p style="font-size:1.2em;"><b style="font-size:1.1em;">Issue:</b> <span style="color:#BB0000;" id="_eaglercraftX_crashReason"></span><br /></p><p style="margin-left:10px;font:0.9em monospace;" id="_eaglercraftX_crashUserAgent"></p><p style="margin-left:10px;font:0.9em monospace;" id="_eaglercraftX_crashWebGL"></p><p style="margin-left:10px;font:0.9em monospace;">Current Date: '+
(new Date).toLocaleString()+'</p><p><br /><span style="font-size:1.1em;border-bottom:1px dashed #AAAAAA;padding-bottom:5px;">Things you can try:</span></p><ol><li><span style="font-weight:bold;">Just try using Eaglercraft on a different device</span>, it isn\'t a bug it\'s common sense</li><li style="margin-top:7px;">If this screen just appeared randomly, try restarting your browser or device</li><li style="margin-top:7px;">If you are not using Chrome/Edge, try installing the latest Google Chrome</li><li style="margin-top:7px;">If your browser is out of date, please update it to the latest version</li></ol></div>';
g.querySelector("#_eaglercraftX_crashReason").appendChild(document.createTextNode(a));try{var q=window.navigator.userAgent}catch(C){q="<error>"}g.querySelector("#_eaglercraftX_crashUserAgent").appendChild(document.createTextNode(q));ab&&ab();window.__curEaglerX188UnloadListenerCB=null;a="No GL_RENDERER string could be queried";try{const C=document.createElement("canvas");C.width=64;C.height=64;const L=C.getContext("webgl");if(L){if(L.getExtension("WEBGL_debug_renderer_info"))var w=L.getParameter(37446);
else(w=L.getParameter(WebGLRenderingContext.RENDERER))&&(w+=" [masked]");w&&(a=w)}}catch(C){}g.querySelector("#_eaglercraftX_crashWebGL").appendChild(document.createTextNode(a))}else alert("Compatibility error: "+a)}}var dc=null;
function Yb(){if(dc)return dc;try{var a=La,b=Ma;if(!a){b=!1;var d=document.createElement("canvas");d.width=64;d.height=64;a=d.getContext("webgl2");a||(a=d.getContext("webgl"),a||(b=!0,a=d.getContext("experimental-webgl")))}return a?(d="",0<Na&&(d+="webgl.version = "+a.getParameter(7938)+"\n"),d=a.getExtension("WEBGL_debug_renderer_info")?d+("webgl.renderer = "+a.getParameter(37446)+"\nwebgl.vendor = "+a.getParameter(37445)+"\n"):d+("webgl.renderer = "+a.getParameter(7937)+" [masked]\nwebgl.vendor = "+
a.getParameter(7936)+" [masked]\n"),0<Na?(d+="\nwebgl.version.id = "+Na+"\nwebgl.experimental = "+b,200===Na?d+="\nwebgl.ext.ANGLE_instanced_arrays = "+!!a.getExtension("ANGLE_instanced_arrays")+"\nwebgl.ext.EXT_color_buffer_half_float = "+!!a.getExtension("EXT_color_buffer_half_float")+"\nwebgl.ext.EXT_shader_texture_lod = "+!!a.getExtension("EXT_shader_texture_lod")+"\nwebgl.ext.OES_fbo_render_mipmap = "+!!a.getExtension("OES_fbo_render_mipmap")+"\nwebgl.ext.OES_texture_float = "+!!a.getExtension("OES_texture_float")+
"\nwebgl.ext.OES_texture_half_float = "+!!a.getExtension("OES_texture_half_float")+"\nwebgl.ext.OES_texture_half_float_linear = "+!!a.getExtension("OES_texture_half_float_linear"):300<=Na&&(d+="\nwebgl.ext.EXT_color_buffer_float = "+!!a.getExtension("EXT_color_buffer_float")+"\nwebgl.ext.EXT_color_buffer_half_float = "+!!a.getExtension("EXT_color_buffer_half_float")+"\nwebgl.ext.OES_texture_float_linear = "+!!a.getExtension("OES_texture_float_linear")),d+="\nwebgl.ext.EXT_texture_filter_anisotropic = "+
!!a.getExtension("EXT_texture_filter_anisotropic")+"\n"):d+="webgl.ext.ANGLE_instanced_arrays = "+!!a.getExtension("ANGLE_instanced_arrays")+"\nwebgl.ext.EXT_color_buffer_float = "+!!a.getExtension("EXT_color_buffer_float")+"\nwebgl.ext.EXT_color_buffer_half_float = "+!!a.getExtension("EXT_color_buffer_half_float")+"\nwebgl.ext.EXT_shader_texture_lod = "+!!a.getExtension("EXT_shader_texture_lod")+"\nwebgl.ext.OES_fbo_render_mipmap = "+!!a.getExtension("OES_fbo_render_mipmap")+"\nwebgl.ext.OES_texture_float = "+
!!a.getExtension("OES_texture_float")+"\nwebgl.ext.OES_texture_float_linear = "+!!a.getExtension("OES_texture_float_linear")+"\nwebgl.ext.OES_texture_half_float = "+!!a.getExtension("OES_texture_half_float")+"\nwebgl.ext.OES_texture_half_float_linear = "+!!a.getExtension("OES_texture_half_float_linear")+"\nwebgl.ext.EXT_texture_filter_anisotropic = "+!!a.getExtension("EXT_texture_filter_anisotropic")+"\n",dc=d):dc="Failed to query GPU info!\n"}catch(g){return dc="ERROR: could not query webgl info - "+
g+"\n"}}function Zb(a){try{var b=window.navigator[a]}catch(d){b="<error>"}return"window.navigator."+a+" = "+b+"\n"}function $b(){try{var a=[];if("object"===typeof navigator.plugins){var b=navigator.plugins.length;if(0<b)for(var d=0;d<b;++d){var g=navigator.plugins[d];a.push({name:g.name,filename:g.filename,desc:g.description})}}var q=JSON.stringify(a)}catch(w){q="<error>"}return"window.navigator.plugins = "+q+"\n"}
function bc(a){try{var b=window.screen[a]}catch(d){b="<error>"}return"window.screen."+a+" = "+b+"\n"}function cc(){try{var a=window.location.href}catch(b){a="<error>"}return"window.location.href = "+a+"\n"}function ac(a){try{var b=window[a]}catch(d){b="<error>"}return"window."+a+" = "+b+"\n"};function ec(a,b,d){const g=document.createElement("a");g.style.position="absolute";g.style.left="0px";g.style.top="0px";g.style.zIndex="-100";g.style.color="transparent";g.innerText="Download File";g.href=b;g.target="_blank";g.download=a;K.appendChild(g);setTimeout(function(){g.click();setTimeout(function(){K.removeChild(g)},50);d&&setTimeout(d,6E4)},50)}var fc=0,gc=null,hc=null,ic=null,jc=null;
function Ib(a,b){if(ic)jc&&jc(a,b);else for(a={msg:a,err:b,next:null},hc&&(hc.next=a),gc||=a,hc=a,++fc;256<fc;)--fc,gc&&=gc.next}
function Kb(){function a(){C=!1;L=null;null!==O?(K.removeChild(O),G=O=null):null!==G&&(K.removeChild(G),G=null)}function b(f){try{window.localStorage&&window.localStorage.setItem(fa,f?"true":"false")}catch(m){}}function d(){try{if(window.localStorage){const f=window.localStorage.getItem(fa);return f&&"true"===f.toLowerCase()}return!1}catch(f){return!1}}function g(){if(ic)ic.focus();else{var f=Math.round(1E3*window.devicePixelRatio);const m=Math.round(400*window.devicePixelRatio);if(ic=window.open("",
"_blank","top="+Math.round((window.screen.height-m)/2)+",left="+Math.round((window.screen.width-f)/2)+",width="+f+",height="+m+",menubar=0,status=0,titlebar=0,toolbar=0")){ic.focus();P=ic.document;P.write('<!DOCTYPE html><html><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Debug Console</title><link type="image/png" rel="shortcut icon" href="'+Ia+'" /></head><body style="overflow-x:hidden;overflow-y:scroll;padding:0px;"><p id="loggerMessageContainer" style="overflow-wrap:break-word;white-space:pre-wrap;font:14px monospace;padding:10px;"></p></body></html>');
P.close();B=P.body;X=P.getElementById("loggerMessageContainer");for(f=gc;f;)q(f.msg+"\n",f.err?"#DD0000":"#000000"),f=f.next;hc=gc=null;fc=0;w();f=()=>{null!=ic&&(ic=null,b(!1))};ic.addEventListener("beforeunload",f);ic.addEventListener("unload",f)}else h("Logger popup was blocked!"),window.alert("ERROR: Popup blocked!\n\nPlease make sure you have popups enabled for this site!")}}function q(f,m){var t=P.createElement("span");t.innerText=f;t.style.color=m;X.appendChild(t);for(f=X.children;2048<f.length;)f[0].remove()}
function w(){setTimeout(()=>{ic.scrollTo(0,B.scrollHeight||B.clientHeight)},1)}A.setClipboard=function(f){try{if(window.navigator.clipboard)return window.navigator.clipboard.writeText(f),!0}catch(m){h("Failed to set clipboard data!")}return!1};A.getClipboard=new WebAssembly.Suspending(async function(){var f=null;try{window.navigator.clipboard&&(f=await navigator.clipboard.readText())}catch(m){h("Failed to read clipboard data!")}return f});var C=!1,L=null,G=null,O=null;A.displayFileChooser=function(f,
m){a();if(Ya){const p=O=document.createElement("div");p.classList.add("_eaglercraftX_mobile_file_chooser_popup");p.style.position="absolute";p.style.backgroundColor="white";p.style.fontFamily="sans-serif";p.style.top="10%";p.style.left="10%";p.style.right="10%";p.style.border="5px double black";p.style.padding="15px";p.style.textAlign="left";p.style.fontSize="20px";p.style.userSelect="none";p.style.zIndex="150";var t=document.createElement("h3");t.appendChild(document.createTextNode("File Chooser"));
p.appendChild(t);t=document.createElement("p");const r=G=document.createElement("input");r.type="file";r.accept=null===f?"."+m:f;r.multiple=!1;t.appendChild(r);p.appendChild(t);f=document.createElement("p");m=document.createElement("button");m.classList.add("_eaglercraftX_mobile_file_chooser_btn_cancel");m.style.fontSize="1.0em";m.addEventListener("click",function(){O===p&&(K.removeChild(p),G=O=null)});m.appendChild(document.createTextNode("Cancel"));f.appendChild(m);f.appendChild(document.createTextNode(" "));
m=document.createElement("button");m.classList.add("_eaglercraftX_mobile_file_chooser_btn_done");m.style.fontSize="1.0em";m.style.fontWeight="bold";m.addEventListener("click",function(){if(O===p){if(0<r.files.length){const l=r.files[0];l.arrayBuffer().then(function(v){C=!0;L={fileName:l.name,fileData:v}}).catch(function(){C=!0;L=null})}else C=!0,L=null;K.removeChild(p);G=O=null}});m.appendChild(document.createTextNode("Done"));f.appendChild(m);p.appendChild(f);K.appendChild(p)}else{const p=G=document.createElement("input");
p.type="file";p.style.position="absolute";p.style.left="0px";p.style.top="0px";p.style.zIndex="-100";p.accept=null===f?"."+m:f;p.multiple=!1;p.addEventListener("change",function(){if(G===p){if(0<p.files.length){const r=p.files[0];r.arrayBuffer().then(function(l){C=!0;L={fileName:r.name,fileData:l}}).catch(function(){C=!0;L=null})}else C=!0,L=null;K.removeChild(p);G=null}});K.appendChild(p);window.setTimeout(function(){p.click()},50)}};A.fileChooserHasResult=function(){return C};A.getFileChooserResult=
function(){C=!1;const f=L;L=null;return f};A.clearFileChooserResult=a;A.downloadFileWithNameU8=function(f,m){const t=URL.createObjectURL(new Blob([m],{type:"application/octet-stream"}));ec(f,t,function(){URL.revokeObjectURL(t)})};A.downloadFileWithNameA=function(f,m){const t=URL.createObjectURL(new Blob([m],{type:"application/octet-stream"}));ec(f,t,function(){URL.revokeObjectURL(t)})};A.downloadScreenshot=function(f,m){ec(f,m.toDataURL("image/png"),null)};var P=null,B=null,X=null;const fa=yb+".showDebugConsole",
D=Ab?"beforeunload":"unload";try{window.addEventListener(D,()=>{if(ic){var f=ic;X=B=P=ic=null;f.close()}})}catch(f){}(zb||d())&&g();vb=function(){b(!0);g()};jc=function(f,m){var t=ic.innerHeight+ic.pageYOffset>=B.offsetHeight;q(f+"\n",m?"#DD0000":"#000000");t&&w()};A.showDebugConsole=vb;A.addLogMessage=Ib;A.isShowingDebugConsole=function(){return!!ic};A.getFaviconURL=function(){return Ia};A.setResetSettingsCallback=function(){return{call:function(f){wb=f}}}};wa.getEPKFileData=function(a){const b=Fa[a];Fa[a]=null;return b};wa.getEPKFileCount=function(){return Fa.length};
if("undefined"!==typeof window){wa.loadImageFile0=new WebAssembly.Suspending(function(a,b){return new Promise(function(d){const g=URL.createObjectURL(new Blob([a],{type:b}));if(g){const q=document.createElement("img");q.addEventListener("load",function(){URL.revokeObjectURL(g);d({width:q.width,height:q.height,img:q})});q.addEventListener("error",function(){URL.revokeObjectURL(g);d(null)});q.src=g}else d(null)})});var kc=null,lc=null;wa.loadImageFile1=function(a,b){const d=a.width,g=a.height;if(a=
a.img)kc||=document.createElement("canvas"),kc.width<d&&(kc.width=d),kc.height<g&&(kc.height=g),lc||(lc=kc.getContext("2d",{willReadFrequently:!0}),lc.imageSmoothingEnabled=!1),lc.clearRect(0,0,d,g),lc.drawImage(a,0,0,d,g),b.set(lc.getImageData(0,0,d,g).data,0)}}else z(wa,"loadImageFile0"),z(wa,"loadImageFile1");var mc=null;
function Lb(a){xa.getContext=function(){return a};xa.initKeepAliveHack=function(b,d){b=URL.createObjectURL(new Blob([T.slice(b,b+d)],{type:"audio/wav"}));d=document.createElement("audio");d.classList.add("_eaglercraftX_keepalive_hack");d.setAttribute("style","display:none;");d.autoplay=!1;d.loop=!0;d.addEventListener("seeked",function(){});d.addEventListener("canplay",function(){mc&&"hidden"===document.visibilityState&&mc.play()});const g=document.createElement("source");g.type="audio/wav";g.src=
b;d.appendChild(g);K.appendChild(d);mc=d};xb=function(){mc&&("hidden"===document.visibilityState?mc.play():mc.pause())};xa.setupPanner=function(b,d,g,q,w){b.maxDistance=d;b.rolloffFactor=1;b.panningModel="HRTF";b.distanceModel="linear";b.coneInnerAngle=360;b.coneOuterAngle=0;b.coneOuterGain=0;b.setOrientation(0,1,0);b.setPosition(g,q,w)};xa.registerIsEndedHandler=function(b,d){d.selfEndHandler||(d.selfEndHandler=function(){d.isEnded=!0});b.addEventListener("ended",d.selfEndHandler)};xa.releaseIsEndedHandler=
function(b,d){d.selfEndHandler&&b.removeEventListener("ended",d.selfEndHandler)};xa.decodeAudioBrowser=new WebAssembly.Suspending(function(b,d){return new Promise(function(g){const q=new Uint8Array(b.length);q.set(b,0);a.decodeAudioData(q.buffer,g,function(){h("Failed to load audio: {}",d);g(null)})})})}function Mb(){xa.getContext=function(){return null};z(xa,"setupPanner");z(xa,"initKeepAliveHack");z(xa,"registerIsEndedHandler");z(xa,"releaseIsEndedHandler");z(xa,"decodeAudioBrowser")};function nc(a){return"string"===typeof a?a:"undefined"===typeof a?null:"string"===typeof a[0]?a[0]:null}function oc(a){return"undefined"===typeof a?null:"undefined"===typeof a.data?null:a.data}
ya.openDB=new WebAssembly.Suspending(function(a){return new Promise(function(b){if("undefined"===typeof indexedDB)b({failedInit:!0,failedLocked:!1,failedError:"IndexedDB not supported",database:null});else{try{var d=indexedDB.open(a,1)}catch(q){b({failedInit:!0,failedLocked:!1,failedError:"Exception opening database",database:null});return}var g=b;d.addEventListener("success",function(){g&&g({failedInit:!1,failedLocked:!1,failedError:null,database:d.result});g=null});d.addEventListener("blocked",
function(){g&&g({failedInit:!1,failedLocked:!0,failedError:"Database is locked",database:null});g=null});d.addEventListener("error",function(){g&&g({failedInit:!0,failedLocked:!1,failedError:"Opening database failed",database:null});g=null});d.addEventListener("upgradeneeded",function(){d.result.createObjectStore("filesystem",{keyPath:["path"]})})}})});
function pc(a,b){return new Promise(function(d){const g=a.transaction("filesystem","readwrite").objectStore("filesystem").delete([b]);g.addEventListener("success",function(){d(!0)});g.addEventListener("error",function(){d(!1)})})}ya.eaglerDelete=new WebAssembly.Suspending(pc);
function qc(a,b){return new Promise(function(d){const g=a.transaction("filesystem","readonly").objectStore("filesystem").get([b]);g.addEventListener("success",function(){d(oc(g.result))});g.addEventListener("error",function(){d(null)})})}ya.eaglerRead=new WebAssembly.Suspending(qc);
function rc(a,b,d){return new Promise(function(g){const q=a.transaction("filesystem","readwrite").objectStore("filesystem").put({path:b,data:d});q.addEventListener("success",function(){g(!0)});q.addEventListener("error",function(){g(!1)})})}ya.eaglerWrite=new WebAssembly.Suspending(function(a,b,d,g){return rc(a,b,T.slice(d,d+g))});
ya.eaglerExists=new WebAssembly.Suspending(function(a,b){return new Promise(function(d){const g=a.transaction("filesystem","readonly").objectStore("filesystem").count([b]);g.addEventListener("success",function(){d(0<g.result)});g.addEventListener("error",function(){d(!1)})})});ya.eaglerMove=new WebAssembly.Suspending(async function(a,b,d){const g=await qc(a,b);return g&&await rc(a,d,g)?await pc(a,b):!1});
ya.eaglerCopy=new WebAssembly.Suspending(async function(a,b,d){return(b=await qc(a,b))&&await rc(a,d,b)});ya.eaglerSize=new WebAssembly.Suspending(function(a,b){return new Promise(function(d){const g=a.transaction("filesystem","readonly").objectStore("filesystem").get([b]);g.addEventListener("success",function(){const q=oc(g.result);d(q?q.byteLength:-1)});g.addEventListener("error",function(){d(-1)})})});
function sc(a){if(0===a.length)return-1;for(var b=0,d=0,g=a.length;d<g;++d)47===a.charCodeAt(d)&&++b;return b}
ya.eaglerIterate=new WebAssembly.Suspending(function(a,b,d){return new Promise(function(g){const q=[],w=a.transaction("filesystem","readonly").objectStore("filesystem").openCursor(),C=0===b.length,L=d?-1:sc(b);w.addEventListener("success",function(){const G=w.result;if(null===G||null===G.key)g({length:q.length,getRow:function(P){return q[P]}});else{var O=nc(G.key);null!=O&&(!C&&!O.startsWith(b)||!d&&sc(O)!==L||q.push(O));G.continue()}});w.addEventListener("error",function(){g(null)})})});async function Nb(){function a(){var e=window.devicePixelRatio;.01>e&&(e=1);fa=X=0;for(var u=S;u&&!isNaN(u.offsetLeft)&&!isNaN(u.offsetTop);)X+=u.offsetLeft-u.scrollLeft,fa+=u.offsetTop-u.scrollTop,u=u.offsetParent;u=K.clientWidth*e|0;var Q=K.clientHeight*e|0,M=0,U=0,ka=u,ea=Q;if(ha){ea=window.visualViewport;var V=ea.scale;M=ea.pageLeft*e*V;U=ea.pageTop*e*V;ka=ea.width*e*V;ea=ea.height*e*V;1>ka&&(ka=1);1>ea&&(ea=1);0>M?(ka+=M,M=0):M>=u&&(M=u-1);0>U?(ea+=U,U=0):U>=Q&&(U=Q-1);M+ka>u&&(ka=u-M);U+ea>
Q&&(ea=Q-U)}V={eventTypeMask:0};J!==e&&(J=e,V.eventTypeMask|=4,V.windowDPI=e);if(x!==u||R!==Q)x=u,R=Q,V.eventTypeMask|=1,V.windowWidth=u,V.windowHeight=Q;if(ja!==M||Aa!==U||Pa!==ka||Ba!==ea)ja=M,Aa=U,Pa=ka,Ba=ea,V.eventTypeMask|=2,V.visualViewportX=M,V.visualViewportY=U,V.visualViewportW=ka,V.visualViewportH=ea;0!==V.eventTypeMask&&Y(0,9,V)}function b(e){const u=e.length,Q=Array(u);for(var M=0;M<u;++M){const U=e.item(M);Q[M]={pointX:U.pageX-X,pointY:U.pageY-fa,radius:.5*(U.radiusX+U.radiusY),force:U.force,
pointUID:U.identifier}}return Q}function d(e,u){return{eventType:e,keyCode:u.code||null,keyName:u.key||null,legacyCode:"number"===typeof u.which?u.which:"number"===typeof u.keyCode?u.keyCode:0,location:u.location,mods:(u.ctrlKey?1:0)|(u.shiftKey?2:0)|(u.metaKey?4:0)}}function g(){return new Promise(function(e){if(-1!==y)throw Error("Main thread is already waiting for VSync!");const u=[!1];window.requestAnimationFrame(function(){u[0]||(u[0]=!0,-1!==y&&(window.clearTimeout(y),y=-1),e())});y=window.setTimeout(function(){u[0]||
(u[0]=!0,y=-1,e())},20)})}function q(e){return new Promise(function(u){setTimeout(u,e)})}function w(e){if(0<e&&1E3>=e){const Q=1E3/e;if(0===da)da=performance.now()+Q;else{e=performance.now();var u=da-e|0;if(0<u)return!Fb&&tc?uc().then(function(){var M=performance.now(),U=da-M|0;if(0<U)return q(U).then(function(){var ka=performance.now();(da+=Q)<ka&&(da=ka)});(da+=Q)<M&&(da=M)}):q(u).then(function(){var M=performance.now();(da+=Q)<M&&(da=M)});(da+=Q)<e&&(da=e)}}else da=0;return Fb?vc(0):uc()}function C(e){if(ta){ua=
!!e;var u=performance.now()|0;if(e){qa=!0;try{S.requestPointerLock()}catch(Q){}-1!==na&&window.clearTimeout(na);na=-1;3E3>u-Qa&&(na=window.setTimeout(function(){try{S.requestPointerLock()}catch(Q){}},3100-(u-Qa)))}else if(-1!==na&&window.clearTimeout(na),na=-1,!qa)try{document.exitPointerLock()}catch(Q){}}}function L(){if(Ca)if(Z.matches){if(k)try{navigator.keyboard.unlock()}catch(e){}try{document.exitFullscreen()}catch(e){}}else{if(k)try{navigator.keyboard.lock()}catch(e){}try{S.requestFullscreen()}catch(e){}}}
function G(){P()?O():f?(f.blur(),f.value="",setTimeout(function(){f&&(D?D.removeChild(f):f.remove(),f=null);D&&(K.removeChild(D),D=null)},10)):(D&&(K.removeChild(D),D=null),D=document.createElement("form"),D.setAttribute("autocomplete","off"),D.classList.add("_eaglercraftX_text_input_wrapper"),D.style.position="absolute",D.style.top="0px",D.style.left="0px",D.style.right="0px",D.style.bottom="0px",D.style.zIndex="-100",D.style.margin="0px",D.style.padding="0px",D.style.border="none",D.addEventListener("submit",
function(e){e.preventDefault();e.stopPropagation();e=e.timeStamp;e&&(0!==r&&10>e-r||0!==l&&10>e-l||0!==v&&10>e-v)||(p||(c("Note: Generating return keystroke from submit event on form, this browser probably doesn't generate keydown/beforeinput/input when enter/return is pressed on the on-screen keyboard"),p=!0),Y(0,3,{eventType:0,absoluteCode:28,absoluteChar:10}))}),f=document.createElement("input"),f.type="password",f.value=" ",f.classList.add("_eaglercraftX_text_input_element"),f.setAttribute("autocomplete",
"off"),f.style.position="absolute",f.style.top="0px",f.style.left="0px",f.style.right="0px",f.style.bottom="0px",f.style.zIndex="-100",f.style.margin="0px",f.style.padding="0px",f.style.border="none",f.style.setProperty("-webkit-touch-callout","default"),f.addEventListener("beforeinput",function(e){if(f===e.target){m||(c("Note: Caught beforeinput event from on-screen keyboard, browser probably does not generate global keydown/keyup events on text fields, or does not respond to cancelling keydown"),
m=!0);var u=e.timeStamp;if(u){if(0!==r&&10>u-r)return;l=u}e.preventDefault();e.stopPropagation();switch(e.inputType){case "insertParagraph":case "insertLineBreak":Y(0,3,{eventType:0,absoluteCode:28,absoluteChar:10});break;case "deleteWordBackward":case "deleteSoftLineBackward":case "deleteHardLineBackward":case "deleteEntireSoftLine":case "deleteContentBackward":case "deleteContent":Y(0,3,{eventType:0,absoluteCode:14,absoluteChar:0});break;case "deleteWordForward":case "deleteSoftLineForward":case "deleteHardLineForward":case "deleteContentForward":Y(0,
3,{eventType:0,absoluteCode:211,absoluteChar:0});break;case "insertText":case "insertCompositionText":case "insertReplacementText":(e=e.data)&&0<e.length&&Y(0,3,{eventType:1,codepoints:e});break;case "insertFromPaste":case "insertFromPasteAsQuotation":case "insertFromDrop":case "insertFromYank":case "insertLink":(e=e.data)&&0<e.length&&Y(0,4,e);break;case "historyUndo":case "historyRedo":case "deleteByDrag":case "deleteByCut":break;default:c('Ignoring InputEvent.inputType "{}" from on-screen keyboard',
e.inputType)}}}),f.addEventListener("input",function(e){if(f===e.target){t||(c("Note: Caught legacy input events from on-screen keyboard, browser could be outdated and doesn't support beforeinput event, or does not respond to cancelling beforeinput"),t=!0);if(e=e.timeStamp){if(0!==r&&10>e-r||0!==l&&10>e-l)return;v=e}e=f.value;var u=e.length;0===u?Y(0,3,{eventType:0,absoluteCode:14,absoluteChar:0}):1===u?Y(0,3,{eventType:1,codepoints:e}):(e=e.trim(),u=e.length,0===u?Y(0,3,{eventType:0,absoluteCode:57,
absoluteChar:32}):Y(0,3,{eventType:1,codepoints:e.charAt(u-1)}));f.value=" ";f.setSelectionRange(1,1)}}),f.addEventListener("focus",function(e){f===e.target&&(f.value=" ",f.setSelectionRange(1,1))}),f.addEventListener("select",function(e){f===e.target&&(e.preventDefault(),e.stopPropagation(),f.value=" ",f.setSelectionRange(1,1))}),D.appendChild(f),K.appendChild(D),f.value=" ",f.focus(),f.select(),f.setSelectionRange(1,1))}function O(){if(f){f.blur();f.value="";const e=f,u=D;window.setTimeout(function(){null!==
u?(u.removeChild(e),u.remove()):e.remove()},10);D=f=null}else D&&(K?K.removeChild(D):D.remove(),D=null)}function P(){return!!f&&document.activeElement===f}var B=null,X=0,fa=0,D=null,f=null,m=!1,t=!1,p=!1,r=0,l=0,v=0,x=-1,R=-1,J=-1,ha=!1,ja=-1,Aa=-1,Pa=-1,Ba=-1,ta=!1,ua=!1,qa=!1,Qa=0,na=-1,Ca=!1,Z=null,k=!1,n=!1,y=-1,E=!1,N=null,W=null,oa=null,Ja=null,bb=null,cb=null,db=null,eb=null,fb=null,gb=null,hb=null,ib=null,jb=null,kb=null,lb=null,mb=null,nb=null,ob=null,pb=null,qb=null,rb=null,sb=null,tb=null,
ub=null;B=document.createElement("div");B.classList.add("_eaglercraftX_keyboard_open_zone");B.style.display="none";B.style.position="absolute";B.style.backgroundColor="transparent";B.style.top="0px";B.style.left="0px";B.style.width="0px";B.style.height="0px";B.style.zIndex="100";B.style.touchAction="pan-x pan-y";B.style.setProperty("-webkit-touch-callout","none");B.style.setProperty("-webkit-tap-highlight-color","rgba(255, 255, 255, 0)");K.appendChild(B);a();K.addEventListener("contextmenu",N=function(e){e.preventDefault();
e.stopPropagation()});S.addEventListener("mousedown",W=function(e){e.preventDefault();e.stopPropagation();ta&&ua&&document.pointerLockElement!==S?C(1):Y(0,0,{eventType:0,posX:e.offsetX,posY:e.offsetY,button:e.button})});S.addEventListener("mouseup",oa=function(e){e.preventDefault();e.stopPropagation();Y(0,0,{eventType:1,posX:e.offsetX,posY:e.offsetY,button:e.button})});S.addEventListener("mousemove",Ja=function(e){e.preventDefault();e.stopPropagation();Y(0,0,{eventType:2,posX:e.offsetX,posY:e.offsetY,
movementX:e.movementX,movementY:e.movementY})});S.addEventListener("mouseenter",bb=function(){Y(0,7,null)});S.addEventListener("mouseleave",cb=function(){Y(0,8,null)});S.addEventListener("touchstart",db=function(e){e.preventDefault();e.stopPropagation();Y(0,2,{eventType:0,changedTouches:b(e.changedTouches),targetTouches:b(e.targetTouches)});O()});S.addEventListener("touchend",eb=function(e){e.preventDefault();e.stopPropagation();Y(0,2,{eventType:2,changedTouches:b(e.changedTouches),targetTouches:b(e.targetTouches)})});
S.addEventListener("touchmove",fb=function(e){e.preventDefault();e.stopPropagation();Y(0,2,{eventType:1,changedTouches:b(e.changedTouches),targetTouches:b(e.targetTouches)})});S.addEventListener("touchcancel",gb=function(e){Y(0,2,{eventType:2,changedTouches:b(e.changedTouches),targetTouches:b(e.targetTouches)})});S.addEventListener("wheel",ob=function(e){e.preventDefault();e.stopPropagation();Y(0,0,{eventType:3,posX:e.offsetX,posY:e.offsetY,wheel:e.deltaY})});window.addEventListener("blur",qb=function(){Y(0,
6,null)});window.addEventListener("focus",pb=function(){Y(0,5,null)});document.addEventListener("visibilitychange",ub=function(){xb&&xb()});window.addEventListener("keydown",jb=function(e){e.preventDefault();e.stopPropagation();"F11"!==e.key||e.repeat?(Y(0,1,d(e.repeat?2:0,e)),e.timeStamp&&"Unidentified"!==e.key&&(r=e.timeStamp)):L()});window.addEventListener("keyup",kb=function(e){e.preventDefault();e.stopPropagation();Y(0,1,d(1,e))});B.addEventListener("touchstart",lb=function(e){e.preventDefault();
e.stopPropagation()});B.addEventListener("touchend",mb=function(e){e.preventDefault();e.stopPropagation();G()});B.addEventListener("touchmove",nb=function(e){e.preventDefault();e.stopPropagation()});(ta="function"===typeof document.exitPointerLock)?(document.addEventListener("pointerlockchange",rb=function(){window.setTimeout(function(){const e=document.pointerLockElement===S;e||ua&&(Qa=performance.now()|0);ua=e},60);qa=!1}),document.addEventListener("pointerlockerror",sb=function(){qa=!1})):h("Pointer lock is not supported on this browser");
(Ca="function"===typeof document.exitFullscreen)?(Z=window.matchMedia("(display-mode: fullscreen)"),(k=!(!navigator.keyboard||!navigator.keyboard.lock))&&Z.addEventListener("change",tb=function(){Z.matches||navigator.keyboard.unlock()})):h("Fullscreen is not supported on this browser");if("undefined"!==typeof window.visualViewport)if("body"===Ka.tagName.toLowerCase())ha=!0;else{const e=document.body;10>=Math.abs(e.clientWidth-K.clientWidth)&&10>=Math.abs(e.clientHeight-K.clientHeight)&&(ha=!0)}else ha=
!1;ha&&c("Note: Detected game is embedded in body, some screens may be resized to window.visualViewport instead for a better mobile experience");try{await g(),n=!0}catch(e){n=!1}n||h("VSync is not supported on this browser");(E="function"===typeof navigator.getGamepads)?(window.addEventListener("gamepadconnected",hb=function(){Y(0,10,{eventType:0})}),window.addEventListener("gamepaddisconnected",ib=function(e){Y(0,10,{eventType:1,gamepad:e.gamepad})})):h("Gamepad detected as unsupported!");F.keyboardLayoutSupported=
function(){return!(!navigator.keyboard||!navigator.keyboard.getLayoutMap)};F.iterateKeyboardLayout=new WebAssembly.Suspending(async function(){const e=[];try{const u=await navigator.keyboard.getLayoutMap();u&&u.forEach&&u.forEach(function(Q,M){e.push({key:Q,value:M})})}catch(u){}return e});F.updateCanvasSize=function(e,u){S.width!==e&&(S.width=e);S.height!==u&&(S.height=u)};var da=0;F.updatePlatformAndSleep=new WebAssembly.Suspending(function(e,u,Q){a();if("string"!==typeof document.visibilityState||
"visible"===document.visibilityState){if(n&&u)return da=0,g();Q&&La.finish();return 0>=e?(da=0,Fb?vc(0):uc()):w(e)}da=0;return q(50)});F.isVSyncSupported=function(){return n};F.mouseSetGrabbed=C;F.isMouseGrabSupported=function(){return ta};F.isMouseGrabbed=function(){return ua};F.isPointerLocked=function(){return ta&&(qa||document.pointerLockElement===S)};F.supportsFullscreen=function(){return Ca};F.toggleFullscreen=L;F.isFullscreen=function(){return Ca&&Z.matches};F.touchSetOpenKeyboardZone=function(e,
u,Q,M){0!==Q&&0!==M?(B.style.display="block",B.style.top=""+(R-u-M)/J+"px",B.style.left=""+e/J+"px",B.style.width=""+Q/J+"px",B.style.height=""+M/J+"px"):(B.style.display="none",B.style.top="0px",B.style.left="0px",B.style.width="0px",B.style.height="0px")};F.touchCloseDeviceKeyboard=O;F.touchIsDeviceKeyboardOpenMAYBE=P;F.gamepadSupported=function(){return E};F.isVisualViewport=function(){return ha};ab=function(){try{N&&(K.removeEventListener("contextmenu",N),N=null),W&&(S.removeEventListener("mousedown",
W),W=null),oa&&(S.removeEventListener("mouseup",oa),oa=null),Ja&&(S.removeEventListener("mousemove",Ja),Ja=null),bb&&(S.removeEventListener("mouseenter",bb),bb=null),cb&&(S.removeEventListener("mouseleave",cb),cb=null),db&&(S.removeEventListener("touchstart",db),db=null),eb&&(S.removeEventListener("touchend",eb),eb=null),fb&&(S.removeEventListener("touchmove",fb),fb=null),gb&&(S.removeEventListener("touchcancel",gb),gb=null),hb&&(window.removeEventListener("gamepadconnected",hb),hb=null),ib&&(window.removeEventListener("gamepaddisconnected",
ib),ib=null),jb&&(window.removeEventListener("keydown",jb),jb=null),kb&&(window.removeEventListener("keyup",kb),kb=null),lb&&(B.removeEventListener("touchstart",lb),lb=null),mb&&(B.removeEventListener("touchend",mb),mb=null),nb&&(B.removeEventListener("touchmove",nb),nb=null),ob&&(S.removeEventListener("wheel",ob),ob=null),pb&&(window.removeEventListener("focus",pb),pb=null),qb&&(window.removeEventListener("blur",qb),qb=null),ub&&(document.removeEventListener("visibilitychange",ub),ub=null),rb&&(document.removeEventListener("pointerlockchange",
rb),rb=null),sb&&(document.removeEventListener("pointerlockerror",sb),sb=null),tb&&(Z.removeEventListener("change",tb),tb=null)}catch(e){h("Failed to remove event listeners! {}",e)}ab=null}};(function(){function a(){this._socket.close()}function b(l){this._socket.send(l)}function d(l){this._socket.send(l)}function g(){return this._frameCountStr+this._frameCountBin}function q(){const l=this._queue;return l?(l._next===l&&l._prev===l?this._queue=null:(this._queue=l._next,l._prev._next=l._next,l._next._prev=l._prev),l._next=null,l._prev=null,0===l.type?--this._frameCountStr:--this._frameCountBin,l):null}function w(){var l=this._frameCountStr+this._frameCountBin;if(0===l)return null;l=Array(l);
var v=0,x=this._queue;const R=x;do{l[v++]=x;var J=x._next;x._next=null;x._prev=null;x=J}while(x!==R);this._queue=null;this._frameCountBin=this._frameCountStr=0;return l}function C(){this._queue=null;this._frameCountBin=this._frameCountStr=0}function L(l,v){var x=l._queue;if(!x)return null;const R=x;do{var J=x._next;if(x.type===v)return v=x._prev,J===x&&v===x?l._queue=null:(x===R&&(l._queue=J),v._next=J,J._prev=v),x._next=null,x._prev=null,x;x=J}while(x!==R);return null}function G(l,v,x){var R=0,J=
l._queue,ha=J;do{var ja=J._next;J.type===v&&(x[R++]=J);J=ja}while(J!==ha);x.length=R;for(ha=0;ha<R;++ha)J=x[ha],ja=J._next,v=J._prev,ja===J&&v===J?l._queue=null:(J===l._queue&&(l._queue=ja),v._next=ja,ja._prev=v)}function O(){return this._frameCountStr}function P(){if(0===this._frameCountStr)return null;const l=L(this,0);l?--this._frameCountStr:this._frameCountStr=0;return l}function B(){var l=this._frameCountStr;if(0===l)return null;l=Array(l);G(this,0,l);this._frameCountStr=0;return l}function X(){const l=
this._frameCountStr;if(0===l)return null;G(this,0,Array(l));this._frameCountStr=0}function fa(){return this._frameCountBin}function D(){if(0===this._frameCountBin)return null;const l=L(this,1);l?--this._frameCountBin:this._frameCountBin=0;return l}function f(){var l=this._frameCountBin;if(0===l)return null;l=Array(l);G(this,1,l);this._frameCountBin=0;return l}function m(){const l=this._frameCountBin;if(0===l)return null;G(this,1,Array(l));this._frameCountBin=0}function t(l){this._enableStringFrames=
l}function p(l){this._enableBinaryFrames=l}function r(l){const v="string"===typeof l;if(v){if(!this._enableStringFrames)return}else if(!this._enableBinaryFrames)return;l={type:v?0:1,data:l,timestamp:performance.now(),_next:null,_prev:null};const x=this._queue;if(x){const R=x._prev;R._next=l;l._prev=R;l._next=x;x._prev=l}else this._queue=l,l._next=l,l._prev=l;v?++this._frameCountStr:++this._frameCountBin}za.createWebSocketHandle=function(l){let v;try{v=new WebSocket(l)}catch(R){return h("Failed to create WebSocket: {}",
l),la("Exception Caught",R),null}v.binaryType="arraybuffer";const x={state:1,_socket:v,_queue:null,_frameCountStr:0,_frameCountBin:0,_addRecievedFrame:r,_enableStringFrames:!0,_enableBinaryFrames:!0,closeSocket:a,sendStringFrame:b,sendBinaryFrame:d,availableFrames:g,getNextFrame:q,getAllFrames:w,clearFrames:C,availableStringFrames:O,getNextStringFrame:P,getAllStringFrames:B,clearStringFrames:X,availableBinaryFrames:fa,getNextBinaryFrame:D,getAllBinaryFrames:f,clearBinaryFrames:m,setEnableStringFrames:t,
setEnableBinaryFrames:p};v.addEventListener("open",function(){x.state=2});v.addEventListener("message",function(R){x._addRecievedFrame(R.data)});v.addEventListener("close",function(){3!==x.state&&(x.state=0)});v.addEventListener("error",function(){1===x.state&&(x.state=3)});return x}})();function Pb(a,b){var d=Eb;const g=d&&200===b?a.getExtension("OES_vertex_array_object"):null,q=d&&200===b?a.getExtension("ANGLE_instanced_arrays"):null,w=d&&200===b&&null!==q,C=d&&(310===b||300===b)&&null!==a.getExtension("EXT_color_buffer_float"),L=d&&!C&&(310===b||300===b||200===b)&&null!==a.getExtension("EXT_color_buffer_half_float"),G=d&&200===b&&null!==a.getExtension("EXT_shader_texture_lod"),O=d&&200===b&&null!==a.getExtension("OES_fbo_render_mipmap"),P=d&&200===b&&null!==g,B=d&&200===b&&null!==
a.getExtension("OES_texture_float"),X=d&&300<=b&&null!==a.getExtension("OES_texture_float_linear"),fa=d&&200===b&&null!==a.getExtension("OES_texture_half_float"),D=d&&200===b&&null!==a.getExtension("OES_texture_half_float_linear");d=d&&null!==a.getExtension("EXT_texture_filter_anisotropic");const f=null!==a.getExtension("WEBGL_debug_renderer_info"),m=300<=b?0:200===b&&P?1:-1,t=300<=b?0:200===b&&w?1:-1,p=[b,m,t,0,0];if(300<=b||O)p[3]|=4;if(300<=b||G)p[3]|=8;300<=b&&(p[3]|=16);(320<=b||(300<=b||B)&&
(C||L))&&(p[3]|=32);(320<=b||(300<=b||fa)&&C)&&(p[3]|=64);d&&(p[3]|=128);(300<=b||D)&&(p[4]|=1);300<=b&&X&&(p[4]|=2);H.getCapBits=function(l){return p[l]};H.glEnable=a.enable.bind(a);H.glDisable=a.disable.bind(a);H.glClearColor=a.clearColor.bind(a);H.glClearDepth=a.clearDepth.bind(a);H.glClear=a.clear.bind(a);H.glDepthFunc=a.depthFunc.bind(a);H.glDepthMask=a.depthMask.bind(a);H.glCullFace=a.cullFace.bind(a);H.glViewport=a.viewport.bind(a);H.glBlendFunc=a.blendFunc.bind(a);H.glBlendFuncSeparate=a.blendFuncSeparate.bind(a);
H.glBlendEquation=a.blendEquation.bind(a);H.glBlendColor=a.blendColor.bind(a);H.glColorMask=a.colorMask.bind(a);H.glDrawBuffers=300<=b?a.drawBuffers.bind(a):pa("glDrawBuffers");H.glReadBuffer=300<=b?a.readBuffer.bind(a):pa("glReadBuffer");H.glReadPixels=a.readPixels.bind(a);H.glPolygonOffset=a.polygonOffset.bind(a);H.glLineWidth=a.lineWidth.bind(a);H.glGenBuffers=a.createBuffer.bind(a);H.glGenTextures=a.createTexture.bind(a);H.glCreateProgram=a.createProgram.bind(a);H.glCreateShader=a.createShader.bind(a);
H.glCreateFramebuffer=a.createFramebuffer.bind(a);H.glCreateRenderbuffer=a.createRenderbuffer.bind(a);H.glGenQueries=300<=b?a.createQuery.bind(a):pa("glGenQueries");H.glDeleteBuffers=a.deleteBuffer.bind(a);H.glDeleteTextures=a.deleteTexture.bind(a);H.glDeleteProgram=a.deleteProgram.bind(a);H.glDeleteShader=a.deleteShader.bind(a);H.glDeleteFramebuffer=a.deleteFramebuffer.bind(a);H.glDeleteRenderbuffer=a.deleteRenderbuffer.bind(a);H.glDeleteQueries=300<=b?a.deleteQuery.bind(a):pa("glDeleteQueries");
H.glBindBuffer=a.bindBuffer.bind(a);H.glBufferData=a.bufferData.bind(a);H.glBufferSubData=a.bufferSubData.bind(a);H.glEnableVertexAttribArray=a.enableVertexAttribArray.bind(a);H.glDisableVertexAttribArray=a.disableVertexAttribArray.bind(a);H.glVertexAttribPointer=a.vertexAttribPointer.bind(a);H.glActiveTexture=a.activeTexture.bind(a);H.glBindTexture=a.bindTexture.bind(a);H.glTexParameterf=a.texParameterf.bind(a);H.glTexParameteri=a.texParameteri.bind(a);H.glTexImage3D=300<=b?a.texImage3D.bind(a):
pa("glTexImage3D");H.glTexImage2D=a.texImage2D.bind(a);H.glTexSubImage2D=a.texSubImage2D.bind(a);H.glCopyTexSubImage2D=a.copyTexSubImage2D.bind(a);H.glTexStorage2D=300<=b?a.texStorage2D.bind(a):pa("glTexStorage2D");H.glPixelStorei=a.pixelStorei.bind(a);H.glGenerateMipmap=a.generateMipmap.bind(a);H.glShaderSource=a.shaderSource.bind(a);H.glCompileShader=a.compileShader.bind(a);H.glGetShaderi=a.getShaderParameter.bind(a);H.glGetShaderInfoLog=a.getShaderInfoLog.bind(a);H.glUseProgram=a.useProgram.bind(a);
H.glAttachShader=a.attachShader.bind(a);H.glDetachShader=a.detachShader.bind(a);H.glLinkProgram=a.linkProgram.bind(a);H.glGetProgrami=a.getProgramParameter.bind(a);H.glGetProgramInfoLog=a.getProgramInfoLog.bind(a);H.glDrawArrays=a.drawArrays.bind(a);H.glDrawElements=a.drawElements.bind(a);H.glDrawRangeElements=300<=b?a.drawRangeElements.bind(a):pa("glDrawRangeElements");H.glFlush=a.flush.bind(a);H.glScissor=a.scissor.bind(a);H.glBindAttribLocation=a.bindAttribLocation.bind(a);H.glGetAttribLocation=
a.getAttribLocation.bind(a);H.glGetUniformLocation=a.getUniformLocation.bind(a);H.glGetUniformBlockIndex=300<=b?a.getUniformBlockIndex.bind(a):pa("glGetUniformBlockIndex");H.glBindBufferRange=300<=b?a.bindBufferRange.bind(a):pa("glBindBufferRange");H.glUniformBlockBinding=300<=b?a.uniformBlockBinding.bind(a):pa("glUniformBlockBinding");H.glUniform1f=a.uniform1f.bind(a);H.glUniform2f=a.uniform2f.bind(a);H.glUniform3f=a.uniform3f.bind(a);H.glUniform4f=a.uniform4f.bind(a);H.glUniform1i=a.uniform1i.bind(a);
H.glUniform2i=a.uniform2i.bind(a);H.glUniform3i=a.uniform3i.bind(a);H.glUniform4i=a.uniform4i.bind(a);H.glUniformMatrix2fv=a.uniformMatrix2fv.bind(a);H.glUniformMatrix3fv=a.uniformMatrix3fv.bind(a);H.glUniformMatrix4fv=a.uniformMatrix4fv.bind(a);H.glUniformMatrix3x2fv=300<=b?a.uniformMatrix3x2fv.bind(a):pa("glUniformMatrix3x2fv");H.glUniformMatrix4x2fv=300<=b?a.uniformMatrix4x2fv.bind(a):pa("glUniformMatrix4x2fv");H.glUniformMatrix4x3fv=300<=b?a.uniformMatrix4x3fv.bind(a):pa("glUniformMatrix4x3fv");
H.glBindFramebuffer=a.bindFramebuffer.bind(a);H.glCheckFramebufferStatus=a.checkFramebufferStatus.bind(a);H.glBlitFramebuffer=300<=b?a.blitFramebuffer.bind(a):pa("glBlitFramebuffer");H.glRenderbufferStorage=a.renderbufferStorage.bind(a);H.glFramebufferTexture2D=a.framebufferTexture2D.bind(a);H.glFramebufferTextureLayer=300<=b?a.framebufferTextureLayer.bind(a):pa("glFramebufferTextureLayer");H.glBindRenderbuffer=a.bindRenderbuffer.bind(a);H.glFramebufferRenderbuffer=a.framebufferRenderbuffer.bind(a);
H.glGetError=a.getError.bind(a);H.getAllExtensions=a.getSupportedExtensions.bind(a);H.isContextLost=a.isContextLost.bind(a);const r=[];w&&r.push("ANGLE_instanced_arrays");C&&r.push("EXT_color_buffer_float");L&&r.push("EXT_color_buffer_half_float");G&&r.push("EXT_shader_texture_lod");O&&r.push("OES_fbo_render_mipmap");P&&r.push("OES_vertex_array_object");B&&r.push("OES_texture_float");X&&r.push("OES_texture_float_linear");fa&&r.push("OES_texture_half_float");D&&r.push("OES_texture_half_float_linear");
d&&r.push("EXT_texture_filter_anisotropic");f&&r.push("WEBGL_debug_renderer_info");H.dumpActiveExtensions=function(){return r};H.glGetInteger=function(l){l=a.getParameter(l);return"number"===typeof l?l:0};H.glGetString=function(l){if(f)switch(l){case 7936:l=a.getParameter(37445);null==l&&(l=a.getParameter(7936));break;case 7937:l=a.getParameter(37446);null==l&&(l=a.getParameter(7937));break;default:l=a.getParameter(l)}else l=a.getParameter(l);return"string"===typeof l?l:null};switch(m){case 0:H.glGenVertexArrays=
a.createVertexArray.bind(a);H.glDeleteVertexArrays=a.deleteVertexArray.bind(a);H.glBindVertexArray=a.bindVertexArray.bind(a);break;case 1:H.glGenVertexArrays=g.createVertexArrayOES.bind(g);H.glDeleteVertexArrays=g.deleteVertexArrayOES.bind(g);H.glBindVertexArray=g.bindVertexArrayOES.bind(g);break;default:z(H,"glGenVertexArrays"),z(H,"glDeleteVertexArrays"),z(H,"glBindVertexArray")}switch(t){case 0:H.glVertexAttribDivisor=a.vertexAttribDivisor.bind(a);H.glDrawArraysInstanced=a.drawArraysInstanced.bind(a);
H.glDrawElementsInstanced=a.drawElementsInstanced.bind(a);break;case 1:H.glVertexAttribDivisor=q.vertexAttribDivisorANGLE.bind(q);H.glDrawArraysInstanced=q.drawArraysInstancedANGLE.bind(q);H.glDrawElementsInstanced=q.drawElementsInstancedANGLE.bind(q);break;default:z(H,"glVertexAttribDivisor"),z(H,"glDrawArraysInstanced"),z(H,"glDrawElementsInstanced")}};var tc=!1;const wc=new MessageChannel;var xc=null;wc.port2.addEventListener("message",function(){xc()});async function Jb(){wc.port1.start();wc.port2.start();xc=function(){xc=null};wc.port1.postMessage(0);xc?await new Promise(function(a){setTimeout(function(){xc?h("Immediate continue hack is not supported"):tc=!0;a()},25)}):h("Immediate continue hack is not supported")}Da.getRootElement=function(){return Ka};Da.getParentElement=function(){return K};Da.getCanvasElement=function(){return S};
Da.getEaglercraftXOpts=function(){return I};Da.getEventCount=Tb.A.bind(Tb);Da.getNextEvent=Tb.s.bind(Tb);
Da.queueAsyncDownload=function(a,b,d){try{fetch(a,{cache:b?"force-cache":"no-store",mode:"cors"}).then(function(g){return g.arrayBuffer()}).then(function(g){Y(1,0,{requestId:d,arrayBuffer:g})}).catch(function(g){h("Failed to complete async download: {}",a);la("Exception Caught",g);Y(1,0,{requestId:d,arrayBuffer:null})})}catch(g){h("Failed to fetch: {}",a),la("Exception Caught",g),Y(1,0,{requestId:d,arrayBuffer:null})}};
Da.download=new WebAssembly.Suspending(function(a,b){return new Promise(function(d){try{fetch(a,{cache:b?"force-cache":"no-store",mode:"cors"}).then(function(g){return g.arrayBuffer()}).then(function(g){d(g)}).catch(function(g){h("Failed to complete download: {}",a);la("Exception Caught",g);d(null)})}catch(g){h("Failed to fetch: {}",a),la("Exception Caught",g),d(null)}})});Da.writeCrashReport=function(a){Xb(a,!1)};
Da.showContextLostScreen=function(a){if(!Za){Za=!0;var b=K||Ka;if(b){var d=document.createElement("img"),g=document.createElement("div");d.setAttribute("style","z-index:100;position:absolute;top:10px;left:calc(50% - 151px);");d.src=Ha;g.setAttribute("style","z-index:100;position:absolute;top:135px;left:10%;right:10%;bottom:50px;background-color:white;border:1px solid #cccccc;overflow-x:hidden;overflow-y:scroll;font:18px sans-serif;padding:40px;");g.classList.add("_eaglercraftX_context_lost_element");
b.appendChild(d);b.appendChild(g);b.appendChild(Vb());g.innerHTML='<h2><svg style="vertical-align:middle;margin:0px 16px 8px 8px;" xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48" fill="none"><path stroke="#000000" stroke-width="3" stroke-linecap="square" d="M1.5 8.5v34h45v-28m-3-3h-10v-3m-3-3h-10m15 6h-18v-3m-3-3h-10"/><path stroke="#000000" stroke-width="2" stroke-linecap="square" d="M12 21h0m0 4h0m4 0h0m0-4h0m-2 2h0m20-2h0m0 4h0m4 0h0m0-4h0m-2 2h0"/><path stroke="#000000" stroke-width="2" stroke-linecap="square" d="M20 30h0 m2 2h0 m2 2h0 m2 2h0 m2 -2h0 m2 -2h0 m2 -2h0"/></svg> + WebGL context lost!</h2><div style="margin-left:40px;"><p style="font-size:1.2em;">Your browser has forcibly released all of the resources allocated by the game\'s 3D rendering context. EaglercraftX cannot continue, please refresh the page to restart the game, sorry for the inconvenience.</p><p style="font-size:1.2em;">This is not a bug, it is usually caused by the browser deciding it no longer has sufficient resources to continue rendering this page. If it happens again, try closing your other browser tabs and windows.</p><p style="font-size:1.2em;">If you\'re playing with vsync disabled, try enabling vsync to allow the browser to control the GPU usage more precisely.</p><p style="overflow-wrap:break-word;white-space:pre-wrap;font:0.75em monospace;margin-top:1.5em;" id="_eaglercraftX_contextLostTrace"></p></div>';
g.querySelector("#_eaglercraftX_contextLostTrace").appendChild(document.createTextNode(a))}else alert("WebGL context lost!"),h("WebGL context lost!")}};Da.steadyTimeMillis=performance.now.bind(performance);function vc(a){return new Promise(function(b){setTimeout(b,a)})}Da.sleep=new WebAssembly.Suspending(vc);function yc(a){tc?(xc=a,wc.port1.postMessage(0)):setTimeout(a,0)}function uc(){return new Promise(yc)}Da.immediateContinue=new WebAssembly.Suspending(uc);Da.immediateContinueSupported=function(){return tc};
Da.setCrashReportString=function(a,b){$a[a]=b};va.getByteBufferView=function(a,b){return new Int8Array(T,a,b)};va.getUnsignedByteBufferView=function(a,b){return new Uint8Array(T,a,b)};va.getUnsignedClampedByteBufferView=function(a,b){return new Uint8ClampedArray(T,a,b)};va.getShortBufferView=function(a,b){return new Int16Array(T,a,b)};va.getUnsignedShortBufferView=function(a,b){return new Uint16Array(T,a,b)};va.getIntBufferView=function(a,b){return new Int32Array(T,a,b)};va.getFloatBufferView=function(a,b){return new Float32Array(T,a,b)};
va.setHeapViewCallback=function(a){Xa=a;Sb()};var zc;
(function(){function a(f){let m=P.get(f);"undefined"===typeof m&&(m=new Function("return "+f+";"),P.set(f,m));return m()}function b(f,m){let t={exports:null,G:m,h:null,j:null};d(f);g(f);q(f,t);w(f,t);f.teavmMath=Math;return{u(p){t.exports=p},F(p){t.h=p},D(p){t.j=p}}}function d(f){f.teavmDate={currentTimeMillis:()=>(new Date).getTime(),dateToString:m=>(new Date(m)).toString(),getYear:m=>(new Date(m)).getFullYear(),setYear:(m,t)=>{m=new Date(m);m.setFullYear(t);return m.getTime()},getMonth:m=>(new Date(m)).getMonth(),
setMonth:(m,t)=>{m=new Date(m);m.setMonth(t);return m.getTime()},getDate:m=>(new Date(m)).getDate(),setDate:(m,t)=>{m=new Date(m);m.setDate(t);return m.getTime()},create:(m,t,p,r,l,v)=>(new Date(m,t,p,r,l,v)).getTime(),createFromUTC:(m,t,p,r,l,v)=>Date.UTC(m,t,p,r,l,v)}}function g(f){let m=[],t=[];f.teavmConsole={putcharStderr:function(p){10===p?(p=String.fromCharCode(...m),console.error(p),ca&&ca(p,!0),m.length=0):m.push(p)},putcharStdout:function(p){10===p?(p=String.fromCharCode(...t),console.log(p),
ca&&ca(p,!1),t.length=0):t.push(p)}}}function q(f,m){let t=new FinalizationRegistry(r=>{let l=m.exports["teavm.reportGarbageCollectedValue"];"undefined"!==typeof l&&m.j(function(){l(r.B,r.C)})}),p=new FinalizationRegistry(r=>{let l=m.exports["teavm.reportGarbageCollectedString"];"function"===typeof l&&m.j(function(){l(r)})});f.teavm={createWeakRef:(r,l,v)=>{null!==v&&t.register(r,{C:l,B:v});return new WeakRef(r)},deref:r=>{r=r.deref();return void 0!==r?r:null},createStringWeakRef:(r,l)=>{p.register(r,
l);return new WeakRef(r)},stringDeref:r=>r.deref(),takeStackTrace:()=>{var r=Error().stack;let l=[];for(let v of r.split("\n"))r=B.exec(v),null!==r&&2<=r.length&&l.push(parseInt(r[1],16));return{getStack:function(){let v;if(m.h)try{v=m.h(l)}catch(x){console.warn("Could not deobfuscate stack",x)}v||=l.map(x=>({className:"java.lang.Throwable$FakeClass",method:"fakeMethod",file:"Throwable.java",line:x}));return v}}},decorateException:r=>{new fa(m,r)},linearMemory:()=>m.exports["teavm.memory"].buffer,
notifyHeapResized:()=>{}}}function w(f,m){function t(k){return k}function p(k){var n=k.charAt(0);var y=""+(r(n)?n:"_");for(n=1;n<k.length;++n){let N=k.charAt(n);var E=N;E=r(E)||"0"<=E&&"9">=E;y+=E?N:"_"}return y}function r(k){return"A"<=k&&"Z">=k||"a"<=k&&"z">=k||"_"===k||"$"===k}function l(k,n,y){null===k?(new Function("value",n+" = value;"))(y):k[n]=y}function v(k){m.exports["teavm.js.throwException"](X in k?k[X]:m.exports["teavm.js.wrapException"](k))}function x(k){a:{if(k instanceof WebAssembly.Exception){var n=
m.exports["teavm.javaException"];var y=m.exports["teavm.getJsException"];if(k.is(n)){k=k.getArg(n,0);n=m.exports["teavm.js.extractException"](k);if(null!==n){y=n;break a}y=y(k);"undefined"===typeof y&&(y=new fa(m,k));break a}}y=k}throw y;}function R(k){var n=[];for(let y=0;y<k.length;++y)n.push("p"+y);n=0===n.length?"":n.join(", ");n=(new Function("rethrowJavaAsJs","fn",`return function(${n}) {\n`+"    try {\n"+`        return fn(${n});\n`+"    } catch (e) {\n        rethrowJavaAsJs(e);\n    }\n};"))(x,
k);n.__impl=k;n.__rethrow=x;return n}function J(k,n){return(new Function("constructor",`return function ${k}(marker, javaObject) {\n`+"    return constructor.call(this, marker, javaObject);\n}\n"))(n)}function ha(k){try{return k()}catch(n){v(n)}}let ja=Symbol("javaObject"),Aa=Symbol("functions"),Pa=Symbol("functionOrigin"),Ba=Symbol("wrapperCallMarker"),ta=new WeakMap,ua=new WeakMap,qa=new Map,Qa=new FinalizationRegistry(k=>qa.delete(k)),na=new WeakMap,Ca=2463534242;f.teavmJso={stringBuiltinsSupported:()=>
{if(null===D){let k=new Int8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,2,23,1,14,119,97,115,109,58,106,115,45,115,116,114,105,110,103,4,99,97,115,116,0,0,3,1,0,5,4,1,1,0,0,10,-127,-128,-128,0,0]);D=!WebAssembly.validate(k,{builtins:["js-string"]})}return D},isUndefined:k=>"undefined"===typeof k,emptyArray:()=>[],appendToArray:(k,n)=>k.push(n),unwrapBoolean:k=>k?1:0,wrapBoolean:k=>!!k,getProperty:function(k,n){try{return null!==k?k[n]:a(n)}catch(y){v(y)}},setProperty:l,setPropertyPure:l,global:k=>{try{return a(k)}catch(n){v(n)}},
createClass:(k,n,y)=>{k=p(k||"JavaObject");let E;E=null===n?function(W){this[ja]=W;this[Aa]=null}:function(W){n.call(this,W)};let N=J(k,function(W,oa){if(W===Ba)E.call(this,oa);else{if(null===y)throw Error("This class can't be instantiated directly");try{return y.apply(null,arguments)}catch(Ja){x(Ja)}}});N.prototype=Object.create(n||Object.prototype);N.prototype.constructor=N;k=J(k,function(W){return N.call(this,Ba,W)});k[Ba]=N;k.prototype=N.prototype;return k},exportClass:k=>k[Ba],defineMethod:(k,
n,y)=>{let E=[];for(let N=1;N<y.length;++N)E.push("p"+N);k.prototype[n]=(new Function("rethrowJavaAsJs","fn",`return function(${0===E.length?"":E.join(", ")}) {\n`+"    try {\n"+`        return fn(${["this",E].join(", ")});\n`+"    } catch (e) {\n        rethrowJavaAsJs(e);\n    }\n};"))(x,y)},defineStaticMethod:(k,n,y)=>{k[n]=R(y)},defineFunction:R,defineProperty:(k,n,y,E)=>{let N={get(){try{return y(this)}catch(W){x(W)}}};null!==E&&(N.set=function(W){try{E(this,W)}catch(oa){x(oa)}});Object.defineProperty(k.prototype,
n,N)},defineStaticProperty:(k,n,y,E)=>{let N={get(){try{return y()}catch(W){x(W)}}};null!==E&&(N.set=function(W){try{E(W)}catch(oa){x(oa)}});Object.defineProperty(k,n,N)},javaObjectToJS:(k,n)=>{if(null===k)return null;var y=ta.get(k);if("undefined"!=typeof y&&(y=y.deref(),"undefined"!==typeof y))return y;n=new n(k);ta.set(k,new WeakRef(n));return n},unwrapJavaObject:k=>k[ja],asFunction:(k,n)=>{let y=k[Aa];null===y&&(y=Object.create(null),k[Aa]=y);let E=y[n];"function"!==typeof E&&(E=function(){return k[n].apply(k,
arguments)},E[Pa]=k,y[n]=E);return E},functionAsObject:(k,n)=>{let y=k[Pa];if("undefined"!==typeof y){let E=y[Aa];if(void 0!==E&&E[n]===k)return y}return{[n]:function(...E){try{return k(...E)}catch(N){x(N)}}}},wrapObject:k=>{if(null===k)return null;if("object"===typeof k||"function"===typeof k){var n=k[ja];if("object"===typeof n)return n;n=ua.get(k);if(void 0!==n&&(n=n.deref(),void 0!==n))return n;n=m.exports["teavm.jso.createWrapper"](k);ua.set(k,new WeakRef(n));return n}n=qa.get(k);if(void 0!==
n&&(n=n.deref(),void 0!==n))return n;n=m.exports["teavm.jso.createWrapper"](k);qa.set(k,new WeakRef(n));Qa.register(n,k);return n},isPrimitive:(k,n)=>typeof k===n,instanceOf:(k,n)=>k instanceof n,instanceOfOrNull:(k,n)=>null===k||k instanceof n,sameRef:(k,n)=>k===n,hashCode:k=>{if("object"===typeof k||"function"===typeof k||"symbol"===typeof k){var n=na.get(k);if("number"===typeof n)return n;n=Ca;n^=n<<13;n^=n>>>17;Ca=n^=n<<5;na.set(k,n);return n}return"number"===typeof k?k|0:"bigint"===typeof k?
BigInt.asIntN(32,k):"boolean"===typeof k?k?1:0:0},apply:(k,n,y)=>{try{return null===k?a(n)(...y):k[n](...y)}catch(E){v(E)}},concatArray:(k,n)=>[...k,...n],getJavaException:k=>k[X],getJSException:k=>(0,m.exports["teavm.getJsException"])(k),jsExports:()=>m.G};for(var Z of"wrapByte wrapShort wrapChar wrapInt wrapLong wrapFloat wrapDouble unwrapByte unwrapShort unwrapChar unwrapInt unwrapLong unwrapFloat unwrapDouble".split(" "))f.teavmJso[Z]=t;Z=[];for(let k=0;32>k;++k){let n=0===Z.length?"":Z.join(", "),
y=[...Z,"body"].join(", ");f.teavmJso["createFunction"+k]=(new Function("wrapCallFromJavaToJs",...Z,"body",`return new Function('wrapCallFromJavaToJs', ${y}).bind(this, wrapCallFromJavaToJs);`)).bind(null,ha);f.teavmJso["bindFunction"+k]=(E,...N)=>E.bind(null,...N);f.teavmJso["callFunction"+k]=(new Function("rethrowJsAsJava","fn",...Z,"try {\n"+`    return fn(${n});\n`+"} catch (e) {\n    rethrowJsAsJava(e);\n}")).bind(null,v);f.teavmJso["callMethod"+k]=(new Function("rethrowJsAsJava","getGlobalName",
"instance","method",...Z,"try {\n     return instance !== null\n"+`        ? instance[method](${n})\n`+`        : getGlobalName(method)(${n});\n`+"} catch (e) {\n    rethrowJsAsJava(e);\n}")).bind(null,v,a);f.teavmJso["construct"+k]=(new Function("rethrowJsAsJava","constructor",...Z,"try {\n"+`    return new constructor(${n});\n`+"} catch (e) {\n    rethrowJsAsJava(e);\n}")).bind(null,v);f.teavmJso["arrayOf"+k]=new Function(...Z,"return ["+n+"]");Z.push("p"+(k+1))}}async function C(f){try{const m=
{},t=b(m,{}),p=f.path instanceof WebAssembly.Module?f.path:await WebAssembly.compileStreaming(fetch(f.path),{builtins:["js-string"]}),r=new WebAssembly.Instance(p,m);t.u(r.exports);return{module:p,instance:r}}catch(m){return console.warn("Could not load deobfuscator",m),null}}function L(f,m,t){let p=null,r=!1;return l=>{if(!r){r=!0;if(null!==m)try{p=t.exports.createFromExternalFile.value(m)}catch(v){console.warn("Could not load create deobfuscator",v)}if(null===p&&null!==f)try{p=t.exports.createForModule.value(f)}catch(v){console.warn("Could not create deobfuscator from module data",
v)}}return null!==p?p.deobfuscate(l):[]}}async function G(f,m){if(!m.enabled||"auto"!==f&&"external"!==f)return null;if(m.l instanceof ArrayBuffer)return new Int8Array(m.l);f=await fetch(m.l);return f.ok?new Int8Array(await f.arrayBuffer()):null}function O(f){const m=new sa;f.teavm.pollAsyncCallbacks=function(){for(var t;t=m.s();)t.fn()};return function(t){m.push({fn:t,_next:null})}}let P=new Map,B=/.+:wasm-function\[[0-9]+]:0x([0-9a-f]+).*/,X=Symbol("javaException");class fa extends Error{constructor(f,
m){super();this.g=f;this[X]=m;f.exports["teavm.setJsException"](m,this)}get message(){var f=this.g.exports["teavm.exceptionMessage"];return"function"===typeof f&&(f=f(this[X]),null!=f)?f:"(could not fetch message)"}}let D=null;zc={load:async function(f,m){m||={};var t=m.h||{};let [p,r,l]=await Promise.all([t.enabled?C(t):Promise.resolve(null),f instanceof WebAssembly.Module?Promise.resolve(f):WebAssembly.compileStreaming(fetch(f),{builtins:["js-string"]}),G(t.v,t)]);var v={};f={};t=b(v,f);"undefined"!==
typeof m.o&&m.o(v);t.D(O(v));m=await WebAssembly.instantiate(r,v);t.u(m.exports);p&&(v=L(null,l,p.instance),null!==v&&(t.F(v),f.deobfuscator=v));t={exports:f,instance:m,L:{H:r,K:p?p.module:null}};for(let x in m.exports){let R=m.exports[x];R instanceof WebAssembly.Global?Object.defineProperty(f,x,{get:()=>R.value}):"function"===typeof R&&(f[x]=R)}f.memory=m.exports["teavm.memory"];f.I=l;return t},J:b,M:function(f){return new Proxy(f,{get(m,t){return new WebAssembly.Global({value:"externref",mutable:!1},
m[t])}})}}})();async function Ac(){try{Error.stackTraceLimit=1024;I=self.__eaglercraftXLoaderContext.getEaglercraftXOpts();self.__eaglercraftXLoaderContext.getEagRuntimeJSURL();const a=self.__eaglercraftXLoaderContext.getClassesWASMURL(),b=self.__eaglercraftXLoaderContext.getClassesDeobfWASMURL(),d=self.__eaglercraftXLoaderContext.getClassesTEADBGURL();Fa=self.__eaglercraftXLoaderContext.getEPKFiles();Ka=self.__eaglercraftXLoaderContext.getRootElement();self.__eaglercraftXLoaderContext.getImageURL(0);Ga=self.__eaglercraftXLoaderContext.getImageURL(1);
Ha=self.__eaglercraftXLoaderContext.getImageURL(2);Ia=self.__eaglercraftXLoaderContext.getImageURL(3);const g=self.__eaglercraftXLoaderContext.getMainArgs();delete self.__eaglercraftXLoaderContext;if("_worker_process_"!==g[0]){if(!await Hb())return}else ba="worker",await Qb();c("Loading EaglercraftX WASM GC binary...");const q=await zc.load(a,{h:{enabled:!(!b||!d),path:b,v:"external",l:d},o:function(w){w.WASMGCBufferAllocator=va;w.platformApplication=A;w.platformAssets=wa;w.platformAudio=xa;w.platformFilesystem=
ya;w.platformInput=F;w.platformNetworking=za;w.platformOpenGL=H;w.platformRuntime=Da;w.teavm.notifyHeapResized=function(){Rb(q.exports.memory)}}});Rb(q.exports.memory);Ea=q.exports.deobfuscator;c("Calling entry point with args: {}",JSON.stringify(g));try{await WebAssembly.promising(q.exports.main.__impl)(g)}catch(w){q.exports.main.__rethrow(w)}finally{ia(2,"Main function has returned!",[])}}catch(a){Wb(a)}}
"object"===typeof self.__eaglercraftXLoaderContext?self.__eaglercraftXLoaderContext.runMain(Ac):console.error("???");}).call(this);
